spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
      enabled: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/tg_bot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000

app:
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    access_expiration: 86400
    refresh_expiration: 2592000
    tokenType: Bearer

storage:
  upload_dir: uploads
senderbot:
  base_url: https://api.telegram.org/
  token: ${SENDER_TOKEN:6231264144:AAFVhLGO6Z8_L2AJfttxyIoMDaJlVoh0d0I}
  support: ${SENDER_SUPPORT_CHAT_ID:-821597353}

